### ISSUE TITLE
Failed to start lisp-paredit (Issue #1 still a problem?)

### ISSUE THREAD

**Issue by ghost** [jonspalding/lisp-paredit#6]
The error box tells me to view Issue #1 on github, but it looks like that issue was closed. It's still throwing an error though:

[Enter steps to reproduce below:]
1. Have paredit installed
2. Start atom

**Atom Version**: 1.0.6
**System**: "Arch Linux"
**Thrown From**: [lisp-paredit](https://github.com/jonspalding/lisp-paredit) package, v0.4.5
### Stack Trace

Failed to activate the lisp-paredit package

```
At Cannot read property 'dispose' of null

TypeError: Cannot read property 'dispose' of null
    at disableParedit (/home/jesse/.atom/packages/lisp-paredit/lib/main.coffee:89:16)
    at /home/jesse/.atom/packages/lisp-paredit/lib/main.coffee:52:13
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
    at Object.module.exports.LispParedit.activate (/home/jesse/.atom/packages/lisp-paredit/lib/main.coffee:42:19)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:19)
    at /usr/share/atom/resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:486:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "projectHome": "/home/jesse/Code",
    "ignoredNames": [
      ".*"
    ],
    "disabledPackages": [
      "increment-number"
    ]
  },
  "lisp-paredit": {
    "strict": false,
    "enabled": false
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.8.7
autocomplete-haskell, v0.4.5
autocomplete-python, v0.5.3
docblockr, v0.7.3
haskell-ghc-mod, v0.8.14
highlight-line, v0.11.0
ide-haskell, v0.7.1
linter, v1.5.0
linter-clang, v3.1.3
linter-clojure, v0.0.5
linter-hlint, v0.4.2
linter-pylint, v1.0.0
lisp-paredit, v0.4.5
minimap, v4.13.2
monokai, v0.18.0
project-manager, v2.3.0
vim-mode, v0.59.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by jonspalding** [comment]
Fixed in 0.4.6
